name: indonesia_tech_news
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #icon
  ionicons: ^0.1.2

  #state management
  flutter_bloc: ^8.1.2

  #comparing dart objects
  equatable: ^2.0.5

  #service locator
  get_it: ^7.6.0

  #dateFormat
  intl: ^0.18.1

  #Database
  floor: any

  #make request to api
  retrofit: ^3.0.1

  #Hooks
  flutter_hooks: ^0.18.3

  #chached image
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  retrofit_generator: 3.0.1+1
  build_runner: 2.1.2

flutter:
  uses-material-design: true
