name: indonesia_tech_news
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.0 <4.0.0'

dependencies: 
  cupertino_icons: 1.0.6
  ionicons: 0.2.2
  flutter_bloc: 8.1.4
  equatable: 2.0.5
  get_it: 7.6.7
  intl: 0.19.0
  floor: 1.4.2
  retrofit: 4.1.0
  flutter_hooks: 0.20.5
  cached_network_image: 3.3.1
  flutter: 
    sdk: flutter
  dio: ^5.4.1

dev_dependencies: 
  flutter_lints: ^3.0.0
  retrofit_generator: 8.1.0
  floor_generator: 1.4.2
  build_runner: 2.4.8
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

